'use client'

import { useState } from 'react'
import { ArrowRight, Brain, Check, ChevronLeft, ChevronRight, Flame, Layers3, Menu, Sparkles, Trophy, Users, X } from 'lucide-react'

type Flashcard = { question: string; answer: string }
const topicCards: Record<string, Flashcard[]> = {
  Biología: [{ question: '¿Qué es la fotosíntesis?', answer: 'Es el proceso por el que las plantas convierten la luz en energía química.' }, { question: '¿Qué necesitan las plantas?', answer: 'Luz solar, agua y dióxido de carbono.' }, { question: '¿Qué producen?', answer: 'Glucosa y oxígeno.' }],
  Historia: [{ question: '¿Qué es una fuente histórica?', answer: 'Un objeto, texto o testimonio que ayuda a conocer el pasado.' }, { question: '¿Qué estudia la historia?', answer: 'Los hechos y procesos de las sociedades a través del tiempo.' }, { question: '¿Qué es una línea de tiempo?', answer: 'Una forma de ordenar acontecimientos según cuándo ocurrieron.' }],
  Matemáticas: [{ question: '¿Qué es una fracción?', answer: 'Una forma de representar partes iguales de un todo.' }, { question: '¿Qué indica el denominador?', answer: 'En cuántas partes iguales se divide el todo.' }, { question: '¿Qué indica el numerador?', answer: 'Cuántas partes estamos tomando.' }],
}
const socialDecks = [{ initials: 'LM', name: 'Ejemplo de estudiante', subject: 'Anatomía · Sistema nervioso', cards: '24 tarjetas', color: 'bg-sky-100 text-sky-700' }, { initials: 'JR', name: 'Mazo de muestra', subject: 'Derecho constitucional', cards: '18 tarjetas', color: 'bg-amber-100 text-amber-700' }, { initials: 'SA', name: 'Contenido conceptual', subject: 'Cálculo · Derivadas', cards: '32 tarjetas', color: 'bg-emerald-100 text-emerald-700' }]

function Logo() { return <a href="#inicio" className="flex items-center gap-2 font-semibold tracking-tight text-primary"><span className="grid size-8 place-items-center rounded-xl bg-primary text-primary-foreground"><Layers3 size={17} /></span><span>remind<span className="text-accent">cards</span></span></a> }
export default function RemindCardsLanding() {
  const [topic, setTopic] = useState('Biología'), [generated, setGenerated] = useState(false), [flipped, setFlipped] = useState(false), [activeCard, setActiveCard] = useState(0), [deckIndex, setDeckIndex] = useState(0), [email, setEmail] = useState(''), [joined, setJoined] = useState(false), [menuOpen, setMenuOpen] = useState(false)
  const cards = topicCards[topic], card = cards[activeCard], deck = socialDecks[deckIndex]
  function chooseTopic(item: string) { setTopic(item); setGenerated(false); setFlipped(false); setActiveCard(0) }
  function flipCard() { if (!flipped) { setFlipped(true); window.setTimeout(() => { setActiveCard((current) => (current + 1) % cards.length); setFlipped(false) }, 650) } }
  return <main id="inicio" className="overflow-hidden bg-background text-foreground">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-border/70 bg-background/85 backdrop-blur-lg"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8"><Logo /><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#como-funciona" className="transition hover:text-primary">Cómo funciona</a><a href="#demo" className="transition hover:text-primary">Demo</a><a href="/proceso" className="transition hover:text-primary">Nuestro proceso</a><a href="#impacto" className="transition hover:text-primary">Impacto</a></nav><a href="#espera" className="hidden rounded-full bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground md:block">Únete a la espera</a><button aria-label={menuOpen ? 'Cerrar menú' : 'Abrir menú'} onClick={() => setMenuOpen(!menuOpen)} className="rounded-lg p-2 md:hidden">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div>{menuOpen && <nav className="flex flex-col gap-4 border-t border-border bg-background px-5 py-5 text-sm md:hidden"><a href="#como-funciona" onClick={() => setMenuOpen(false)}>Cómo funciona</a><a href="#demo" onClick={() => setMenuOpen(false)}>Demo</a><a href="/proceso" onClick={() => setMenuOpen(false)}>Nuestro proceso</a><a href="#impacto" onClick={() => setMenuOpen(false)}>Impacto</a></nav>}</header>
    <section className="mx-auto flex min-h-[700px] max-w-6xl items-center px-5 pb-20 pt-36 lg:px-8"><div className="max-w-2xl animate-fade-up"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1.5 text-xs font-medium text-muted-foreground"><Sparkles size={14} className="text-accent" /> Hecho para aprender mejor</div><h1 className="text-balance text-5xl font-semibold leading-[1.04] tracking-[-0.06em] text-primary sm:text-7xl">Convierte tus apuntes en tarjetas que <span className="relative whitespace-nowrap text-accent">sí recuerdas.<span className="absolute -bottom-2 left-0 h-1 w-full rounded-full bg-accent" /></span></h1><p className="mt-8 max-w-lg text-lg leading-8 text-muted-foreground">Estudia con IA, repasa con un tutor virtual y aprende junto a otros estudiantes.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#espera" className="inline-flex items-center justify-center gap-2 rounded-full bg-primary px-6 py-3.5 text-sm font-semibold text-primary-foreground">Quiero estar en la lista de espera <ArrowRight size={17} /></a><a href="#demo" className="inline-flex items-center justify-center rounded-full border border-border bg-card px-6 py-3.5 text-sm font-semibold text-primary">Probar la demo</a></div></div></section>
    <section className="border-y border-border bg-muted/45"><div className="mx-auto flex max-w-6xl flex-wrap justify-between gap-4 px-5 py-5 text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground lg:px-8"><span>Para parciales</span><span>Para finales</span><span>Para aprender de verdad</span><span className="text-accent">Con impacto social</span></div></section>
    <section id="como-funciona" className="bg-primary px-5 py-28 text-primary-foreground lg:px-8"><div className="mx-auto max-w-6xl"><p className="eyebrow text-accent">Así funciona</p><h2 className="mt-3 max-w-xl text-balance text-4xl font-semibold sm:text-5xl">De tus apuntes a una mejor forma de estudiar.</h2><div className="mt-16 grid gap-10 md:grid-cols-3">{[['01', 'Sube tus apuntes', 'Pega o carga el contenido de una clase.'], ['02', 'La IA crea tus flashcards', 'Convierte las ideas importantes en preguntas y respuestas.'], ['03', 'Repasa con tu tutor virtual', 'Recibe retroalimentación y aumenta la dificultad.']].map(([n, t, d]) => <div key={n} className="border-t border-primary-foreground/20 pt-5"><span className="font-mono text-sm text-accent">{n}</span><h3 className="mt-12 text-2xl font-semibold">{t}</h3><p className="mt-3 leading-7 text-primary-foreground/65">{d}</p></div>)}</div></div></section>
    <section id="demo" className="mx-auto max-w-6xl px-5 py-28 lg:px-8"><p className="eyebrow">Pruébalo ahora</p><h2 className="mt-3 max-w-xl text-balance text-4xl font-semibold tracking-[-0.04em] text-primary sm:text-5xl">Elige un tema. Empieza a recordarlo.</h2><div className="mt-12 grid gap-6 rounded-[2rem] border border-border bg-muted/50 p-4 md:grid-cols-[0.8fr_1.2fr] md:p-6"><div className="rounded-3xl bg-card p-6"><label className="text-sm font-semibold text-primary">Elige un tema</label><div className="mt-4 flex flex-wrap gap-2">{Object.keys(topicCards).map((item) => <button key={item} onClick={() => chooseTopic(item)} aria-pressed={topic === item} className={`rounded-full border px-4 py-2 text-sm transition ${topic === item ? 'border-primary bg-primary text-primary-foreground' : 'border-border text-muted-foreground hover:border-primary'}`}>{item}</button>)}</div><button onClick={() => { setGenerated(true); setFlipped(false); setActiveCard(0) }} className="mt-8 flex w-full items-center justify-center gap-2 rounded-full bg-accent px-5 py-3.5 text-sm font-semibold text-accent-foreground"><Sparkles size={17} /> Generar flashcards</button></div><div className="rounded-3xl bg-primary p-6 text-primary-foreground md:p-8"><div className="flex items-center justify-between"><div><p className="text-sm text-primary-foreground/65">Tema seleccionado</p><h3 className="mt-1 text-2xl font-semibold">{topic}</h3></div>{generated && <span className="text-xs text-primary-foreground/65">{activeCard + 1} / {cards.length}</span>}</div>{generated ? <button aria-label="Voltear flashcard" onClick={flipCard} className="card-flip mt-8 w-full text-left [perspective:1000px]"><div className={`relative min-h-64 w-full transition-transform duration-700 [transform-style:preserve-3d] ${flipped ? '[transform:rotateY(180deg)]' : ''}`}><div className="absolute inset-0 flex flex-col justify-between rounded-3xl bg-card p-7 text-primary [backface-visibility:hidden]"><span className="text-xs font-semibold uppercase tracking-[0.16em] text-accent">Pregunta</span><p className="text-2xl font-semibold leading-tight">{card.question}</p><span className="text-xs text-muted-foreground">Haz clic para voltear</span></div><div className="absolute inset-0 flex flex-col justify-between rounded-3xl bg-accent p-7 text-accent-foreground [backface-visibility:hidden] [transform:rotateY(180deg)]"><span className="text-xs font-semibold uppercase tracking-[0.16em]">Respuesta</span><p className="text-xl font-semibold leading-8">{card.answer}</p><span className="text-xs">Avanzando a la siguiente tarjeta…</span></div></div></button> : <div className="mt-8 flex min-h-64 items-center justify-center rounded-3xl border border-dashed border-primary-foreground/25 text-center text-sm text-primary-foreground/60">Tus flashcards aparecerán aquí<br />cuando generes el mazo.</div>}</div></div></section>
    <section id="impacto" className="mx-auto max-w-6xl px-5 py-28 lg:px-8"><div className="grid gap-12 md:grid-cols-2"><div><p className="eyebrow">Nuestro compromiso</p><h2 className="mt-3 text-4xl font-semibold text-primary sm:text-5xl">Cada tarjeta puede ayudar a abrir una puerta.</h2></div><div className="rounded-[2rem] bg-primary p-8 text-primary-foreground"><p className="text-3xl font-semibold text-accent">Una visión con impacto</p><p className="mt-5 text-xl leading-8">Aprender mejor también puede significar que más estudiantes tengan la oportunidad de seguir estudiando.</p></div></div></section>
    <section className="border-t border-border bg-muted/50 px-5 py-24 lg:px-8"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between"><div><p className="eyebrow">Comunidad conceptual</p><h2 className="mt-3 text-3xl font-semibold text-primary">Así podrían verse tus mazos compartidos.</h2></div><div className="flex gap-2"><button aria-label="Mazo anterior" onClick={() => setDeckIndex((deckIndex + 2) % 3)} className="rounded-full border border-border bg-card p-2"><ChevronLeft size={18} /></button><button aria-label="Siguiente mazo" onClick={() => setDeckIndex((deckIndex + 1) % 3)} className="rounded-full border border-border bg-card p-2"><ChevronRight size={18} /></button></div></div><div className="mt-10 flex items-center justify-between rounded-3xl border border-border bg-card p-6"><div className="flex items-center gap-4"><span className={`grid size-12 place-items-center rounded-2xl text-sm font-bold ${deck.color}`}>{deck.initials}</span><div><p className="font-semibold text-primary">{deck.name}</p><p className="text-sm text-muted-foreground">{deck.subject}</p></div></div><span className="text-sm text-muted-foreground">{deck.cards}</span></div></div></section>
    <section id="espera" className="px-5 py-28 lg:px-8"><div className="mx-auto max-w-3xl rounded-[2rem] bg-primary px-6 py-16 text-center text-primary-foreground"><p className="eyebrow text-accent">Muy pronto</p><h2 className="mx-auto mt-3 max-w-xl text-4xl font-semibold sm:text-5xl">Sé de los primeros en estudiar con RemindCards.</h2><p className="mx-auto mt-5 max-w-md leading-7 text-primary-foreground/65">Déjanos tu correo y te avisaremos cuando esté disponible.</p>{joined ? <div className="mx-auto mt-8 flex max-w-md items-center justify-center gap-2 rounded-full bg-primary-foreground/10 px-5 py-4 text-sm"><Check size={18} className="text-accent" /> ¡Listo! Te avisaremos cuando esté disponible.</div> : <form onSubmit={(e) => { e.preventDefault(); setJoined(true) }} className="mx-auto mt-8 flex max-w-md flex-col gap-3 sm:flex-row"><input aria-label="Correo electrónico" type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="tu@correo.com" className="min-w-0 flex-1 rounded-full bg-primary-foreground/10 px-5 py-3.5 text-sm" /><button className="rounded-full bg-accent px-6 py-3.5 text-sm font-semibold text-accent-foreground">Unirme a la lista</button></form>}</div></section>
    <footer className="border-t border-border px-5 py-8"><div className="mx-auto flex max-w-6xl justify-between text-sm text-muted-foreground"><Logo /><p>Hecho para estudiantes, con impacto para estudiantes.</p></div></footer>
  </main>
}
