'use client'

import { useState } from 'react'
import { ChevronDown, Layers3 } from 'lucide-react'

const phases = [
  { title: 'Planeación', person: 'Abigail y William', ikigai: 'Nos apasiona transformar necesidades en proyectos organizados y viables, conectando personas, recursos y estrategias para convertir una idea en un propósito claro.', groups: [['Identificación de la necesidad', 'Identificar la problemática, el público objetivo, sus dificultades, la propuesta de valor, el objetivo general y el alcance inicial.'], ['Investigación y benchmarking', 'Investigar aplicaciones similares, analizar sus funcionalidades, interacción y experiencia de usuario, e identificar oportunidades de mejora y diferenciación.'], ['Definición de la solución', 'Definir funcionalidades principales y del MVP, conversión de apuntes a flashcards, tutor virtual, repaso y medición del progreso.'], ['Recursos, equipo y gestión', 'Seleccionar tecnología, IA, almacenamiento y herramientas; conformar el equipo, definir roles, metodología, backlog, fechas y criterios de éxito.'], ['Arquitectura técnica', 'Definir el flujo de la aplicación, sus componentes, información, integración con IA, almacenamiento, riesgos y medidas de seguridad y privacidad.']] },
  { title: 'Diseño', person: 'Lauren', ikigai: 'Me apasiona convertir ideas en experiencias visuales intuitivas y atractivas, combinando creatividad e innovación para crear soluciones centradas en el usuario.', groups: [['Investigación UX', 'Analizar referentes, escuchar a posibles usuarios e identificar comportamientos, necesidades, dificultades y perfiles.'], ['Arquitectura de experiencia', 'Definir navegación, registro, carga de apuntes, conversión a flashcards, revisión, tutor virtual, dudas y progreso.'], ['Diseño visual', 'Crear el Design System: tipografías, colores, componentes, iconografía, tarjetas, mensajes de IA, pantallas, estados y logo.'], ['Prototipado y validación', 'Crear wireframes y prototipos de alta fidelidad, probar los flujos principales, recoger observaciones y aprobar el diseño final.']] },
  { title: 'Implementación', person: 'William', ikigai: 'Me motiva convertir las ideas en soluciones funcionales mediante la tecnología, construyendo con código herramientas que hagan realidad la visión del proyecto.', groups: [['Preparación técnica', 'Configurar entorno, repositorio, estructura del proyecto, arquitectura, ambientes y documentación para agentes.'], ['Desarrollo de funcionalidades', 'Construir registro, carga y procesamiento de documentos, generación y edición de flashcards, repaso, progreso y perfil.'], ['Tutor virtual con IA', 'Integrar el modelo, prompts, chat, contexto de apuntes, explicaciones y manejo de respuestas fuera de contexto.'], ['Base de datos, seguridad e integración', 'Proteger usuarios y datos, integrar frontend, backend, base de datos, IA y almacenamiento, y verificar los flujos completos.'], ['MVP y piloto', 'Desarrollar el MVP, realizar pruebas internas, corregir errores y preparar el lanzamiento piloto.']] },
  { title: 'Testeo', person: 'Hanner', ikigai: 'Me apasiona descubrir errores y oportunidades de mejora, poniendo cada detalle a prueba para garantizar una solución confiable y satisfactoria.', groups: [['Planificación de pruebas', 'Definir estrategia, criterios de aceptación, casos de prueba y escenarios críticos.'], ['Pruebas funcionales', 'Probar registro, apuntes, flashcards, repaso, progreso, tutor virtual y manejo de errores.'], ['Pruebas de IA', 'Evaluar calidad, correspondencia con apuntes, ausencia de invenciones, preguntas ambiguas y utilidad de respuestas.'], ['Pruebas técnicas y piloto', 'Crear pruebas unitarias, integración y end-to-end; medir rendimiento, compatibilidad y seguridad, y recoger feedback del piloto.']] },
  { title: 'Mantenimiento y mejora continua', person: 'Juanpa', ikigai: 'Me motiva escuchar, analizar y solucionar problemas para impulsar la mejora continua, asegurando que la solución evolucione según las necesidades de sus usuarios.', groups: [['Monitoreo y retroalimentación', 'Monitorear errores, rendimiento e IA; recolectar reseñas, sugerencias y dificultades de uso.'], ['Análisis y priorización', 'Analizar mejoras, priorizar funcionalidades, actualizar el backlog y definir el siguiente ciclo.'], ['Mejora', 'Implementar cambios, hacer regresión, medir impacto y actualizar la documentación.'], ['Medición del producto', 'Medir aceptación, satisfacción, frecuencia de uso, apuntes procesados, flashcards generadas, uso del tutor y retención.']] }]

export default function ProcesoPage() {
  const [open, setOpen] = useState(0)
  return <main className="min-h-screen bg-background text-foreground"><header className="border-b border-border bg-background/90 px-5 py-5 backdrop-blur-lg"><div className="mx-auto flex max-w-6xl items-center justify-between"><a href="/" className="flex items-center gap-2 font-semibold tracking-tight text-primary"><span className="grid size-8 place-items-center rounded-xl bg-primary text-primary-foreground"><Layers3 size={17} /></span>remind<span className="text-accent">cards</span></a><a href="/#espera" className="rounded-full bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground">Únete a la espera</a></div></header><section className="mx-auto max-w-6xl px-5 pb-16 pt-24 lg:px-8"><p className="eyebrow">Cómo construimos la idea</p><h1 className="mt-3 max-w-3xl text-balance text-5xl font-semibold tracking-[-0.06em] text-primary sm:text-7xl">Un proyecto que avanza por etapas.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">Este es el proceso detrás de RemindCards: desde entender el problema hasta mejorar continuamente la experiencia de aprendizaje.</p><div className="mt-14 grid gap-3">{phases.map((phase, index) => <article key={phase.title} className="overflow-hidden rounded-3xl border border-border bg-card"><button onClick={() => setOpen(open === index ? -1 : index)} aria-expanded={open === index} className="flex w-full items-center justify-between gap-5 p-6 text-left md:p-8"><span className="flex items-start gap-5"><span className="font-mono text-sm text-accent">0{index + 1}</span><span><span className="block text-2xl font-semibold text-primary">{phase.title}</span><span className="mt-1 block text-sm text-muted-foreground">{phase.person}</span></span></span><ChevronDown className={`shrink-0 transition-transform ${open === index ? 'rotate-180' : ''}`} /></button>{open === index && <div className="border-t border-border px-6 pb-7 pt-6 md:px-8"><p className="max-w-3xl text-base leading-7 text-muted-foreground"><span className="font-semibold text-primary">Ikigai: </span>{phase.ikigai}</p><div className="mt-7 grid gap-3 md:grid-cols-2">{phase.groups.map(([title, text]) => <div key={title} className="rounded-2xl bg-muted/60 p-5"><h3 className="font-semibold text-primary">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></div>}</article>)}</div></section></main>
}
